#_config.yml

url: "germainedadulla.com"

title: Germaine Dadulla - Portfolio

description: Virtual proof that I am a decent photographer, and an even more decent web dev.

avatar: "camera.png"

author:
	name: Germaine Dadulla

social-network-links:
	rss: true
	twitter: germ_ine
	instagram: germ_ine
	facebook: germaine.dadulla

plugins:
  - jekyll-seo-tag